[features]
seeds = false
skip-lint = false

[programs.localnet]
kyc_dao = "3j93ny9pacByeHi8JCnP34wk7fBVJzyvURktAr3TdfcF"

[programs.devnet]
kycdao_cpi_example = "12ooNXAnRpGcTX1fHBWysVoSzHvmqxZqWy4EQj6PcNyv"
kyc_dao = "3j93ny9pacByeHi8JCnP34wk7fBVJzyvURktAr3TdfcF"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "./utils/keypairs/my-wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
