[features]
seeds = false
skip-lint = false
[programs.devnet]
solana_program = "KKaUCEcxFjGRhbCU83rkS8rUQtVgKLKXC8oKnruBpFm"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/alextnetto/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
