[features]
seeds = false
skip-lint = false
[programs.devnet]
kyc_dao = "8Y7hXQY96Vovp3c1bnsbRvD6Vtp56oG37La1CVfaFBff"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/guilherme/my-solana-wallet/arceuus.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/signatures/**/*.ts"
